name: simple_form_validator
description: Package for simple field validation of flutter forms
version: 0.1.4
homepage: https://github.com/kovaccc/simple-form-validator

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  intl: ^0.18.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0


